package domain

import "time"

// Artifact is a non-ephemeral product generated by a Phenotype (Agent Instance).
// Stored in Content-Addressable Storage (CAS) at data/vault/{hash}.
// Metadata is embedded in pgvector for semantic retrieval. See ADR-0012.
type Artifact struct {
	Hash            string            `json:"hash"`
	ContentType     string            `json:"content_type"`
	SizeBytes       int64             `json:"size_bytes"`
	SessionID       string            `json:"session_id"`
	StepIndex       int               `json:"step_index"`
	Metadata        map[string]string `json:"metadata,omitempty"`
	ParentHash      string            `json:"parent_hash,omitempty"`
	SemanticSummary string            `json:"semantic_summary,omitempty"`
	CreatedAt       time.Time         `json:"created_at"`
	// Tags are the artifact's classification tags, validated on write against the
	// writer's scope + controlled vocabulary and filtered on read by the reader's
	// effective scope. Includes kernel-stamped provenance. ADR-0034 (D8).
	Tags            []string          `json:"tags,omitempty"`
}
