// Mechanical helpers for the setup subcommand (ADR-0122): process execution,
// probes, the uv bootstrap download, embedded-asset unpacking, and the config
// bundle writer. Kept free of prompting/step logic so they are unit-testable.
package app

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"context"
	cryptorand "crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	healthpb "google.golang.org/grpc/health/grpc_health_v1"

	core "github.com/cambrian-sh/core"
)

// Model defaults, kept in sync with configs/embedder.json.example and the
// reranker agent (RERANK_MODEL env overrides the latter).
const (
	setupEmbedderModel = "bge-large"
	setupRerankModel   = "BAAI/bge-reranker-base"
)

// setupComposeYML is the local-Postgres compose file setup generates. It is a
// reduced copy of db/docker-compose.yml: the pagerank-recompute worker is not
// included because its image builds from the source tree, which an installed
// machine does not have — the kernel only READS its table and degrades
// gracefully without it (ADR-0054).
const setupComposeYML = `# Generated by cambrian-orchestrator setup (ADR-0122). Safe to re-generate.
services:
  cambrian-db:
    image: pgvector/pgvector:pg16
    container_name: cambrian-db
    environment:
      POSTGRES_USER: ${CAMBRIAN_DB_USER:-cambrian}
      POSTGRES_PASSWORD: ${CAMBRIAN_DB_PASSWORD:-cambrian}
      POSTGRES_DB: ${CAMBRIAN_DB_NAME:-cambrian_db}
    ports:
      - "${CAMBRIAN_DB_PORT:-5432}:5432"
    volumes:
      - cambrian_data:/var/lib/postgresql/data
    restart: always
volumes:
  cambrian_data:
`

// setupSelfCheckPy is the per-agent import self-check (PLAT-01): for each
// agents/**/requirements.txt, verify every pinned dist is installed in the
// venv, and report which AGENT is missing which package.
const setupSelfCheckPy = `import sys, glob, os
from importlib.metadata import version, PackageNotFoundError
root = sys.argv[1]
miss = {}
for req in glob.glob(os.path.join(root, '**', 'requirements.txt'), recursive=True):
    agent = os.path.basename(os.path.dirname(req)) or 'agents'
    for ln in open(req, encoding='utf-8'):
        ln = ln.strip()
        if not ln or ln.startswith('#') or ln.startswith('-'): continue
        name = ln.split('==')[0].split('>=')[0].split('~=')[0].split('[')[0].strip()
        if not name: continue
        try: version(name)
        except PackageNotFoundError: miss.setdefault(agent, set()).add(name)
for a, ms in miss.items(): print('MISSING\t%s\t%s' % (a, ','.join(sorted(ms))))
`

// ---- process execution & probes ----------------------------------------------------------

// exec runs a command with a timeout and returns trimmed combined output.
func (s *setupState) exec(ctx context.Context, timeout time.Duration, name string, args ...string) (string, bool) {
	cctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	cmd := exec.CommandContext(cctx, name, args...)
	out, err := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)), err == nil
}

// execIn is exec with an explicit working directory (bun install runs in each
// agent package dir, ADR-0125).
func (s *setupState) execIn(ctx context.Context, dir string, timeout time.Duration, name string, args ...string) (string, bool) {
	cctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	cmd := exec.CommandContext(cctx, name, args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)), err == nil
}

// probe checks a tool via `--version` and returns its first output line.
func (s *setupState) probe(ctx context.Context, name string) (string, bool) {
	out, ok := s.exec(ctx, 8*time.Second, name, "--version")
	if !ok {
		return "", false
	}
	return strings.TrimSpace(strings.SplitN(out, "\n", 2)[0]), true
}

func tcpOpen(addr string, timeout time.Duration) bool {
	c, err := net.DialTimeout("tcp", addr, timeout)
	if err != nil {
		return false
	}
	_ = c.Close()
	return true
}

// containsModel reports whether `ollama list` output mentions the model
// (matching the bare name, ignoring any :tag suffix).
func containsModel(list, model string) bool {
	return strings.Contains(list, strings.SplitN(model, ":", 2)[0])
}

// ---- database probes ---------------------------------------------------------------------

func (s *setupState) dbDSN() string {
	u := &url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(s.db.user, s.db.password),
		Host:   net.JoinHostPort(s.db.host, s.db.port),
		Path:   "/" + s.db.dbname,
	}
	return u.String()
}

// dbPing is a real connect+ping (not a TCP probe — Postgres accepts TCP before
// it is ready to authenticate during container start).
func (s *setupState) dbPing(ctx context.Context) error {
	cctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	conn, err := pgx.Connect(cctx, s.dbDSN())
	if err != nil {
		return err
	}
	defer conn.Close(cctx)
	return conn.Ping(cctx)
}

func (s *setupState) waitForDB(ctx context.Context, tries int) bool {
	for range tries {
		if s.dbPing(ctx) == nil {
			return true
		}
		select {
		case <-ctx.Done():
			return false
		case <-time.After(time.Second):
		}
	}
	return false
}

// pgvectorAvailable checks the extension is installable — the migrations
// (ADR-0021/0064) hard-require it, so failing early beats a mid-migrate error.
func (s *setupState) pgvectorAvailable(ctx context.Context) (bool, error) {
	cctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	conn, err := pgx.Connect(cctx, s.dbDSN())
	if err != nil {
		return false, err
	}
	defer conn.Close(cctx)
	var n int
	if err := conn.QueryRow(cctx, "SELECT count(*) FROM pg_available_extensions WHERE name = 'vector'").Scan(&n); err != nil {
		return false, err
	}
	return n > 0, nil
}

// ---- readiness poll ----------------------------------------------------------------------

// pollHealth polls the kernel's grpc.health.v1 overall ("") status until
// SERVING or the deadline. The overall status is DB-gated (internal/health),
// so SERVING proves boot + database, not just an open port. Delegates to
// probeHealth (lifecycle.go), which handles both plaintext and SEC-03 TLS
// kernels.
func (s *setupState) pollHealth(ctx context.Context, addr string, wait time.Duration) bool {
	deadline := time.Now().Add(wait)
	for time.Now().Before(deadline) {
		status, err := probeHealth(ctx, addr, 2*time.Second)
		if err == nil && status == healthpb.HealthCheckResponse_SERVING {
			return true
		}
		select {
		case <-ctx.Done():
			return false
		case <-time.After(time.Second):
		}
	}
	return false
}

// ---- uv bootstrap ------------------------------------------------------------------------

const setupUVBaseURL = "https://github.com/astral-sh/uv/releases/latest/download/"

// uvAsset maps GOOS/GOARCH to the uv release asset name.
func uvAsset(goos, goarch string) (string, bool) {
	arch := map[string]string{"amd64": "x86_64", "arm64": "aarch64"}[goarch]
	if arch == "" {
		return "", false
	}
	switch goos {
	case "linux":
		return "uv-" + arch + "-unknown-linux-gnu.tar.gz", true
	case "windows":
		return "uv-" + arch + "-pc-windows-msvc.zip", true
	case "darwin":
		return "uv-" + arch + "-apple-darwin.tar.gz", true
	}
	return "", false
}

// ensureUV finds uv on PATH or in <prefix>/bin, downloading it there when
// absent. Returns "" (with a warning printed) when uv cannot be provisioned —
// callers fall back to system python/pip.
func (s *setupState) ensureUV(ctx context.Context) string {
	if s.uvBin != "" {
		return s.uvBin
	}
	if p, err := exec.LookPath("uv"); err == nil {
		s.uvBin = p
		return p
	}
	local := filepath.Join(s.prefix, "bin", exeName("uv"))
	if fileExists(local) {
		s.uvBin = local
		return local
	}
	asset, ok := uvAsset(runtime.GOOS, runtime.GOARCH)
	if !ok {
		return ""
	}
	fmt.Print("  downloading uv (package installer)… ")
	tmp, err := downloadTemp(ctx, setupUVBaseURL+asset)
	if err != nil {
		fmt.Println(s.ui.yellow("failed"))
		s.ui.line("warn", "uv download failed", err.Error())
		return ""
	}
	defer os.Remove(tmp)
	if strings.HasSuffix(asset, ".zip") {
		err = extractOneFromZip(tmp, "uv", local)
	} else {
		err = extractOneFromTarGz(tmp, "uv", local)
	}
	if err != nil {
		fmt.Println(s.ui.yellow("failed"))
		s.ui.line("warn", "uv extract failed", err.Error())
		return ""
	}
	_ = os.Chmod(local, 0o755)
	fmt.Println(s.ui.green("done"))
	s.uvBin = local
	return local
}

// ---- bun bootstrap (ADR-0125) --------------------------------------------------------------

const setupBunBaseURL = "https://github.com/oven-sh/bun/releases/latest/download/"

// bunAsset maps GOOS/GOARCH to the official bun release asset name.
func bunAsset(goos, goarch string) (string, bool) {
	arch := map[string]string{"amd64": "x64", "arm64": "aarch64"}[goarch]
	if arch == "" {
		return "", false
	}
	switch goos {
	case "linux", "darwin":
		return "bun-" + goos + "-" + arch + ".zip", true
	case "windows":
		if arch != "x64" {
			return "", false
		}
		return "bun-windows-x64.zip", true
	}
	return "", false
}

// ensureBun finds bun on PATH or in <prefix>/bin. Downloading it there happens
// only when `download` is true (i.e. JS agent units exist — a ~90MB fetch is
// not paid for a Python-only fleet). Returns "" when bun is unavailable.
func (s *setupState) ensureBun(ctx context.Context, download bool) string {
	if s.bunBin != "" {
		return s.bunBin
	}
	if p, err := exec.LookPath("bun"); err == nil {
		s.bunBin = p
		return p
	}
	local := filepath.Join(s.prefix, "bin", exeName("bun"))
	if fileExists(local) {
		s.bunBin = local
		return local
	}
	if !download {
		return ""
	}
	asset, ok := bunAsset(runtime.GOOS, runtime.GOARCH)
	if !ok {
		return ""
	}
	fmt.Print("  downloading bun (JS agent runtime)… ")
	tmp, err := downloadTemp(ctx, setupBunBaseURL+asset)
	if err != nil {
		fmt.Println(s.ui.yellow("failed"))
		s.ui.line("warn", "bun download failed", err.Error())
		return ""
	}
	defer os.Remove(tmp)
	if err := extractOneFromZip(tmp, "bun", local); err != nil {
		fmt.Println(s.ui.yellow("failed"))
		s.ui.line("warn", "bun extract failed", err.Error())
		return ""
	}
	_ = os.Chmod(local, 0o755)
	fmt.Println(s.ui.green("done"))
	s.bunBin = local
	return local
}

// hasJSAgents reports whether any JS agent unit lives under agentsDir: an
// *agent.ts / *agent.js entry file, or any package.json (node_modules skipped).
func hasJSAgents(agentsDir string) bool {
	found := false
	_ = filepath.WalkDir(agentsDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if d.Name() == "node_modules" {
				return fs.SkipDir
			}
			return nil
		}
		n := d.Name()
		if n == "package.json" || strings.HasSuffix(n, "agent.ts") || strings.HasSuffix(n, "agent.js") {
			found = true
			return fs.SkipAll
		}
		return nil
	})
	return found
}

// jsPackageDirs returns every dir under agentsDir carrying a package.json
// (node_modules skipped), agents root first — the union-workspace install
// order (ADR-0125 D6).
func jsPackageDirs(agentsDir string) []string {
	var dirs []string
	_ = filepath.WalkDir(agentsDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() && d.Name() == "node_modules" {
			return fs.SkipDir
		}
		if !d.IsDir() && d.Name() == "package.json" {
			dirs = append(dirs, filepath.Dir(p))
		}
		return nil
	})
	// WalkDir is lexical, which already visits the root before its subtrees;
	// the explicit sort keeps that contract obvious and deterministic.
	slices.Sort(dirs)
	return dirs
}

func downloadTemp(ctx context.Context, rawURL string) (string, error) {
	cctx, cancel := context.WithTimeout(ctx, 5*time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(cctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return "", err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("GET %s: %s", rawURL, resp.Status)
	}
	f, err := os.CreateTemp("", "cambrian-setup-*")
	if err != nil {
		return "", err
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		os.Remove(f.Name())
		return "", err
	}
	if err := f.Close(); err != nil {
		os.Remove(f.Name())
		return "", err
	}
	return f.Name(), nil
}

// extractOneFromZip pulls the single file whose base name matches out of a zip
// archive into dest (0755). Dest is chosen by us, so no zip-slip surface.
func extractOneFromZip(archive, base, dest string) error {
	zr, err := zip.OpenReader(archive)
	if err != nil {
		return err
	}
	defer zr.Close()
	for _, f := range zr.File {
		n := path.Base(f.Name)
		if n != base && n != base+".exe" {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			return err
		}
		defer rc.Close()
		return writeExecutable(dest, rc)
	}
	return fmt.Errorf("%s not found in archive", base)
}

func extractOneFromTarGz(archive, base, dest string) error {
	f, err := os.Open(archive)
	if err != nil {
		return err
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		return err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		if hdr.Typeflag != tar.TypeReg {
			continue
		}
		n := path.Base(hdr.Name)
		if n == base || n == base+".exe" {
			return writeExecutable(dest, tr)
		}
	}
	return fmt.Errorf("%s not found in archive", base)
}

func writeExecutable(dest string, r io.Reader) error {
	out, err := os.OpenFile(dest, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o755)
	if err != nil {
		return err
	}
	// 512MB cap: bounds decompression; the uv binary is ~40MB.
	if _, err := io.Copy(out, io.LimitReader(r, 512<<20)); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

// ---- embedded agents ---------------------------------------------------------------------

// unpackAgents materializes the embedded agent sources into dst, refreshing
// existing files and filtering build junk (__pycache__, *.pyc, node_modules,
// *.map — the JS dependency tree is provisioned by `bun install` at setup
// time, never shipped inside the binary; ADR-0125 D7). Returns the number of
// files written.
func unpackAgents(dst string) (int, error) {
	n := 0
	err := fs.WalkDir(core.AgentsFS, "agents", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "__pycache__" || d.Name() == "node_modules" {
				return fs.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(p, ".pyc") || strings.HasSuffix(p, ".map") {
			return nil
		}
		rel := strings.TrimPrefix(p, "agents/")
		out := filepath.Join(dst, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			return err
		}
		b, err := core.AgentsFS.ReadFile(p)
		if err != nil {
			return err
		}
		if err := os.WriteFile(out, b, 0o644); err != nil {
			return err
		}
		n++
		return nil
	})
	return n, err
}

type setupMissingDep struct{ agent, mods string }

func parseSelfCheck(out string) []setupMissingDep {
	var res []setupMissingDep
	for ln := range strings.SplitSeq(out, "\n") {
		if !strings.HasPrefix(ln, "MISSING\t") {
			continue
		}
		parts := strings.SplitN(strings.TrimSpace(ln), "\t", 3)
		if len(parts) == 3 {
			res = append(res, setupMissingDep{agent: parts[1], mods: parts[2]})
		}
	}
	return res
}

// ---- config bundle -----------------------------------------------------------------------

// writeConfigBundle materializes <prefix>/configs/{config.json,tuning.json}.
// An existing config.json is merged (only the fields setup owns are set), so
// re-running setup never clobbers hand-edits; a fresh install seeds from the
// embedded config.example.json. tuning.json doubles as the ResolveBaseDir
// sentinel, so it is always ensured. Also records the server port for the
// readiness poll.
func (s *setupState) writeConfigBundle() error {
	cfgDir := filepath.Join(s.prefix, "configs")
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return err
	}
	cfgPath := filepath.Join(cfgDir, "config.json")

	var cfg map[string]any
	if b, err := os.ReadFile(cfgPath); err == nil {
		// Windows editors routinely save a UTF-8 BOM; strip it before parsing.
		b = bytes.TrimPrefix(b, []byte{0xEF, 0xBB, 0xBF})
		if uerr := json.Unmarshal(b, &cfg); uerr != nil {
			// Never clobber a file the operator hand-edited: a merge that treats
			// "unparseable" as "absent" silently destroys their config.
			return fmt.Errorf("existing %s is not valid JSON (%v) — fix or remove it; refusing to overwrite", cfgPath, uerr)
		}
	}
	if cfg == nil {
		if b, err := core.ConfigTemplatesFS.ReadFile("configs/config.example.json"); err == nil {
			_ = json.Unmarshal(b, &cfg)
		}
	}
	if cfg == nil {
		cfg = map[string]any{}
	}
	delete(cfg, "_comment")

	cfg["database"] = map[string]any{
		"host": s.db.host, "port": s.db.port, "user": s.db.user,
		"password": s.db.password, "dbname": s.db.dbname,
	}

	dbName := "agents.db"
	if st, ok := cfg["storage"].(map[string]any); ok {
		if v, ok := st["db_name"].(string); ok && v != "" {
			dbName = v
		}
	}
	cfg["storage"] = map[string]any{"data_dir": filepath.Join(s.prefix, "data"), "db_name": dbName}

	met, _ := cfg["metabolism"].(map[string]any)
	if met == nil {
		met = map[string]any{}
	}
	if s.venvPy != "" {
		met["python_executable"] = s.venvPy
	} else if vp := venvPython(filepath.Join(s.prefix, "venv")); fileExists(vp) {
		met["python_executable"] = vp
	}
	// ADR-0125: record the JS runtimes when resolved; absent keys keep the
	// kernel's $PATH fallback.
	if s.bunBin != "" {
		met["bun_executable"] = s.bunBin
	}
	if s.nodeBin != "" {
		met["node_executable"] = s.nodeBin
	}
	met["agents_dir"] = filepath.Join(s.prefix, "agents")
	cfg["metabolism"] = met

	srv, _ := cfg["server"].(map[string]any)
	if srv == nil {
		srv = map[string]any{"port": "50051"}
	}
	cfg["server"] = srv
	if p, ok := srv["port"].(string); ok && p != "" {
		s.serverPort = p
	}

	// Embedder is required to boot (dimensions must be explicit, ADR-0021);
	// default to the local bge-large. An existing block is left untouched.
	if _, ok := cfg["embedder"]; !ok {
		cfg["embedder"] = map[string]any{
			"provider":     "ollama",
			"model":        setupEmbedderModel,
			"endpoint":     "http://localhost:11434",
			"dimensions":   1024,
			"timeout_ms":   10000,
			"query_prefix": "Represent this sentence for searching relevant passages: ",
		}
	}

	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	// 0600, not 0644: this file carries the database password in plaintext,
	// and setup's own .env writer already restricts to owner-only for the same
	// reason. (No effect on Windows ACLs; it protects the Unix installs.)
	if err := os.WriteFile(cfgPath, append(b, '\n'), 0o600); err != nil {
		return err
	}

	tuning := filepath.Join(cfgDir, "tuning.json")
	if !fileExists(tuning) {
		tb, err := core.ConfigTemplatesFS.ReadFile("configs/tuning.json")
		if err != nil {
			tb = []byte("{}\n")
		}
		if err := os.WriteFile(tuning, tb, 0o644); err != nil {
			return err
		}
	}
	return os.MkdirAll(filepath.Join(s.prefix, "data"), 0o755)
}

// ---- .env handling (operator credentials, ADR-0047 D13 seeding) --------------------------

// readEnvFile parses KEY=VALUE lines the way the kernel's LoadDotEnv does:
// blank lines and #-comments skipped, value is everything after the first '='
// with surrounding quotes trimmed. A missing file is an empty map, not an error.
func readEnvFile(path string) (map[string]string, error) {
	out := map[string]string{}
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, err
	}
	for ln := range strings.SplitSeq(string(b), "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		k, v, ok := strings.Cut(ln, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = strings.Trim(strings.TrimSpace(v), `"'`)
	}
	return out, nil
}

// upsertEnvFile sets keys in a .env file, replacing existing assignments and
// appending missing ones, while preserving every unrelated line and comment.
// The file is created 0600 — it holds credentials.
func upsertEnvFile(path string, kv map[string]string) error {
	var lines []string
	if b, err := os.ReadFile(path); err == nil {
		lines = strings.Split(strings.TrimRight(string(b), "\n"), "\n")
		if len(lines) == 1 && lines[0] == "" {
			lines = nil
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	done := map[string]bool{}
	for i, ln := range lines {
		t := strings.TrimSpace(ln)
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		k, _, ok := strings.Cut(t, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		if _, present := kv[k]; present {
			lines[i] = k + "=" + kv[k]
			done[k] = true
		}
	}
	// Deterministic append order for the remaining keys.
	rest := make([]string, 0, len(kv))
	for k := range kv {
		if !done[k] {
			rest = append(rest, k)
		}
	}
	slices.Sort(rest)
	for _, k := range rest {
		lines = append(lines, k+"="+kv[k])
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600)
}

// generatePassword returns a ~24-char URL-safe random password (crypto/rand).
// Setup never mints a FIXED default credential (ADR-0047 D13 secure-by-default).
func generatePassword() (string, error) {
	b := make([]byte, 18)
	if _, err := cryptorand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// ---- small file utils --------------------------------------------------------------------

func exeName(base string) string {
	if runtime.GOOS == "windows" {
		return base + ".exe"
	}
	return base
}

func venvPython(venvDir string) string {
	if runtime.GOOS == "windows" {
		return filepath.Join(venvDir, "Scripts", "python.exe")
	}
	return filepath.Join(venvDir, "bin", "python")
}

func fileExists(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && !fi.IsDir()
}

func isSameFile(a, b string) bool {
	fa, err := os.Stat(a)
	if err != nil {
		return false
	}
	fb, err := os.Stat(b)
	if err != nil {
		return false
	}
	return os.SameFile(fa, fb)
}

// copyFile copies via a temp file + rename so a crash never leaves a truncated
// binary at dest.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	tmp := dst + ".tmp"
	out, err := os.OpenFile(tmp, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o755)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		os.Remove(tmp)
		return err
	}
	if err := out.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, dst); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}

func lastLines(s string, n int) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.TrimSpace(strings.Join(lines, " "))
}
