// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: cambrian.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_Execute_FullMethodName                = "/cambrian.Orchestrator/Execute"
	Orchestrator_RequestProposal_FullMethodName        = "/cambrian.Orchestrator/RequestProposal"
	Orchestrator_QueryMemory_FullMethodName            = "/cambrian.Orchestrator/QueryMemory"
	Orchestrator_ChatStream_FullMethodName             = "/cambrian.Orchestrator/ChatStream"
	Orchestrator_SignalStream_FullMethodName           = "/cambrian.Orchestrator/SignalStream"
	Orchestrator_GenerateViaModelStream_FullMethodName = "/cambrian.Orchestrator/GenerateViaModelStream"
	Orchestrator_GetContextNode_FullMethodName         = "/cambrian.Orchestrator/GetContextNode"
	Orchestrator_PutContextNode_FullMethodName         = "/cambrian.Orchestrator/PutContextNode"
	Orchestrator_RegisterWatch_FullMethodName          = "/cambrian.Orchestrator/RegisterWatch"
	Orchestrator_ListWatches_FullMethodName            = "/cambrian.Orchestrator/ListWatches"
	Orchestrator_DeleteWatch_FullMethodName            = "/cambrian.Orchestrator/DeleteWatch"
	Orchestrator_SetWatchActive_FullMethodName         = "/cambrian.Orchestrator/SetWatchActive"
	Orchestrator_UploadArtifact_FullMethodName         = "/cambrian.Orchestrator/UploadArtifact"
	Orchestrator_GetArtifact_FullMethodName            = "/cambrian.Orchestrator/GetArtifact"
	Orchestrator_ListStepArtifacts_FullMethodName      = "/cambrian.Orchestrator/ListStepArtifacts"
	Orchestrator_IngestMemory_FullMethodName           = "/cambrian.Orchestrator/IngestMemory"
	Orchestrator_ExecuteTool_FullMethodName            = "/cambrian.Orchestrator/ExecuteTool"
	Orchestrator_ListTools_FullMethodName              = "/cambrian.Orchestrator/ListTools"
	Orchestrator_ListSkills_FullMethodName             = "/cambrian.Orchestrator/ListSkills"
	Orchestrator_Embed_FullMethodName                  = "/cambrian.Orchestrator/Embed"
	Orchestrator_WatchApprovals_FullMethodName         = "/cambrian.Orchestrator/WatchApprovals"
	Orchestrator_SubmitApprovalDecision_FullMethodName = "/cambrian.Orchestrator/SubmitApprovalDecision"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// The main method where the agent receives and processes a task (if the Orchestrator also implements this service)
	Execute(ctx context.Context, in *Handoff, opts ...grpc.CallOption) (*Handoff, error)
	// Auction / Qualified-Volunteering Model
	RequestProposal(ctx context.Context, in *AuctionTask, opts ...grpc.CallOption) (*AgentProposal, error)
	// Shared LTM semantic query — proxied through Substrate with ACL enforcement
	QueryMemory(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryResponse, error)
	// Bi-directional TUI shell stream. Upstream: user commands (Handoff).
	// Downstream: real-time telemetry envelope (SymbiosisEvent).
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Handoff, SymbiosisEvent], error)
	// Proactive neural signal stream. Upstream: agent signals (Handoff with _signal_type).
	// Downstream: plan execution telemetry (SymbiosisEvent).
	SignalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Handoff, SymbiosisEvent], error)
	// Managed LLM call: the Substrate acts as a metered proxy, forwarding chunks
	// from the allocated TraitModel to the agent with per-chunk token accounting.
	// ADR-0018.
	GenerateViaModelStream(ctx context.Context, in *GenerateStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error)
	// Resolve a CID from the ContentStore (step results) or LTM pgvector.
	// Used by agents' assemble_context(fetch_fn=agent.substrate.get_context_node).
	// Returns empty data when the CID is unknown. ADR-0022 Phase 3.
	GetContextNode(ctx context.Context, in *ContextNodeRequest, opts ...grpc.CallOption) (*ContextNodeResponse, error)
	// Store a content blob in the ephemeral ContentStore and return its CID
	// (ADR-0048 D4/R7). Used by an agent's working memory to offload a large block
	// and carry a {gist + cid} pointer; the blob is owner-stamped with the caller's
	// session so reads are gated (GetContextNode). Idempotent (content-addressed).
	PutContextNode(ctx context.Context, in *PutContextNodeRequest, opts ...grpc.CallOption) (*PutContextNodeResponse, error)
	// WatchConfig CRUD — premium build only. ADR-0032.
	// Create or replace a reactive rule. Returns the persisted config ID.
	RegisterWatch(ctx context.Context, in *RegisterWatchRequest, opts ...grpc.CallOption) (*RegisterWatchResponse, error)
	// List all registered WatchConfigs.
	ListWatches(ctx context.Context, in *ListWatchesRequest, opts ...grpc.CallOption) (*ListWatchesResponse, error)
	// Delete a WatchConfig by ID.
	DeleteWatch(ctx context.Context, in *DeleteWatchRequest, opts ...grpc.CallOption) (*DeleteWatchResponse, error)
	// Enable or disable a WatchConfig without deleting it.
	SetWatchActive(ctx context.Context, in *SetWatchActiveRequest, opts ...grpc.CallOption) (*SetWatchActiveResponse, error)
	// Artifact storage with ADR-0034 tag-based access scoping. REQ-SDK-007c.
	// Upload validates classification tags against the writer's scope + controlled
	// vocabulary and kernel-stamps provenance before persisting.
	UploadArtifact(ctx context.Context, in *UploadArtifactRequest, opts ...grpc.CallOption) (*UploadArtifactResponse, error)
	// Get an artifact by content hash; returns empty when the caller's effective
	// scope does not permit the artifact's tags (fail-closed).
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error)
	// List artifacts produced by a session+step, scope-filtered for the caller.
	ListStepArtifacts(ctx context.Context, in *ListStepArtifactsRequest, opts ...grpc.CallOption) (*ListStepArtifactsResponse, error)
	// memory.remember() write-back. The kernel DERIVES classification from the
	// agent's DefaultWriteTags (ADR-0035 C2); req.tags is a narrow-only hint.
	IngestMemory(ctx context.Context, in *IngestMemoryRequest, opts ...grpc.CallOption) (*IngestMemoryResponse, error)
	// ADR-0039: kernel-owned tool registry. A cognitive agent invokes a granted
	// system tool with LLM-marshalled args; the kernel authorizes (grant +
	// resource policy + data scope + approval) and runs it in a confined process.
	// The principal is taken from x-agent-id gRPC metadata, never from the body.
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	// ADR-0039: the system tools the calling agent (x-agent-id) may invoke, for
	// building the agent's closed ReAct tool menu. Advisory only — ExecuteTool
	// still authorizes every call. Honors the unrestricted bypass.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// ADR-0046: the system skills the calling agent (x-agent-id) may load, for the
	// agent's [skills] menu section. Tier-1 (summary) by default; Tier-2 (full
	// instructions) for a named skill via use_skill. Scope-gated; agent-local
	// skills are NOT served here (they are SDK-local, the @tools analog).
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	// ADR-0041: embed text into a vector using the kernel's embedder, for the
	// agent's Local Recurrent Workspace relevance ranking. Read-only; no auth impact.
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Operator-plane: stream pending dangerous-tool approval requests (ADR-0039 D10).
	WatchApprovals(ctx context.Context, in *WatchApprovalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApprovalRequest], error)
	// Operator-plane: submit an approve/deny decision for a pending request.
	SubmitApprovalDecision(ctx context.Context, in *ApprovalDecisionRequest, opts ...grpc.CallOption) (*ApprovalDecisionResponse, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) Execute(ctx context.Context, in *Handoff, opts ...grpc.CallOption) (*Handoff, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Handoff)
	err := c.cc.Invoke(ctx, Orchestrator_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) RequestProposal(ctx context.Context, in *AuctionTask, opts ...grpc.CallOption) (*AgentProposal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentProposal)
	err := c.cc.Invoke(ctx, Orchestrator_RequestProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) QueryMemory(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryResponse)
	err := c.cc.Invoke(ctx, Orchestrator_QueryMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Handoff, SymbiosisEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Handoff, SymbiosisEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_ChatStreamClient = grpc.BidiStreamingClient[Handoff, SymbiosisEvent]

func (c *orchestratorClient) SignalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Handoff, SymbiosisEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[1], Orchestrator_SignalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Handoff, SymbiosisEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_SignalStreamClient = grpc.BidiStreamingClient[Handoff, SymbiosisEvent]

func (c *orchestratorClient) GenerateViaModelStream(ctx context.Context, in *GenerateStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[2], Orchestrator_GenerateViaModelStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateStreamRequest, GenerateChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_GenerateViaModelStreamClient = grpc.ServerStreamingClient[GenerateChunk]

func (c *orchestratorClient) GetContextNode(ctx context.Context, in *ContextNodeRequest, opts ...grpc.CallOption) (*ContextNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextNodeResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetContextNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) PutContextNode(ctx context.Context, in *PutContextNodeRequest, opts ...grpc.CallOption) (*PutContextNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutContextNodeResponse)
	err := c.cc.Invoke(ctx, Orchestrator_PutContextNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) RegisterWatch(ctx context.Context, in *RegisterWatchRequest, opts ...grpc.CallOption) (*RegisterWatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWatchResponse)
	err := c.cc.Invoke(ctx, Orchestrator_RegisterWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ListWatches(ctx context.Context, in *ListWatchesRequest, opts ...grpc.CallOption) (*ListWatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchesResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ListWatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DeleteWatch(ctx context.Context, in *DeleteWatchRequest, opts ...grpc.CallOption) (*DeleteWatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWatchResponse)
	err := c.cc.Invoke(ctx, Orchestrator_DeleteWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) SetWatchActive(ctx context.Context, in *SetWatchActiveRequest, opts ...grpc.CallOption) (*SetWatchActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWatchActiveResponse)
	err := c.cc.Invoke(ctx, Orchestrator_SetWatchActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) UploadArtifact(ctx context.Context, in *UploadArtifactRequest, opts ...grpc.CallOption) (*UploadArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadArtifactResponse)
	err := c.cc.Invoke(ctx, Orchestrator_UploadArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ListStepArtifacts(ctx context.Context, in *ListStepArtifactsRequest, opts ...grpc.CallOption) (*ListStepArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStepArtifactsResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ListStepArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) IngestMemory(ctx context.Context, in *IngestMemoryRequest, opts ...grpc.CallOption) (*IngestMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMemoryResponse)
	err := c.cc.Invoke(ctx, Orchestrator_IngestMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, Orchestrator_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) WatchApprovals(ctx context.Context, in *WatchApprovalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApprovalRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[3], Orchestrator_WatchApprovals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchApprovalsRequest, ApprovalRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_WatchApprovalsClient = grpc.ServerStreamingClient[ApprovalRequest]

func (c *orchestratorClient) SubmitApprovalDecision(ctx context.Context, in *ApprovalDecisionRequest, opts ...grpc.CallOption) (*ApprovalDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalDecisionResponse)
	err := c.cc.Invoke(ctx, Orchestrator_SubmitApprovalDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
type OrchestratorServer interface {
	// The main method where the agent receives and processes a task (if the Orchestrator also implements this service)
	Execute(context.Context, *Handoff) (*Handoff, error)
	// Auction / Qualified-Volunteering Model
	RequestProposal(context.Context, *AuctionTask) (*AgentProposal, error)
	// Shared LTM semantic query — proxied through Substrate with ACL enforcement
	QueryMemory(context.Context, *MemoryRequest) (*MemoryResponse, error)
	// Bi-directional TUI shell stream. Upstream: user commands (Handoff).
	// Downstream: real-time telemetry envelope (SymbiosisEvent).
	ChatStream(grpc.BidiStreamingServer[Handoff, SymbiosisEvent]) error
	// Proactive neural signal stream. Upstream: agent signals (Handoff with _signal_type).
	// Downstream: plan execution telemetry (SymbiosisEvent).
	SignalStream(grpc.BidiStreamingServer[Handoff, SymbiosisEvent]) error
	// Managed LLM call: the Substrate acts as a metered proxy, forwarding chunks
	// from the allocated TraitModel to the agent with per-chunk token accounting.
	// ADR-0018.
	GenerateViaModelStream(*GenerateStreamRequest, grpc.ServerStreamingServer[GenerateChunk]) error
	// Resolve a CID from the ContentStore (step results) or LTM pgvector.
	// Used by agents' assemble_context(fetch_fn=agent.substrate.get_context_node).
	// Returns empty data when the CID is unknown. ADR-0022 Phase 3.
	GetContextNode(context.Context, *ContextNodeRequest) (*ContextNodeResponse, error)
	// Store a content blob in the ephemeral ContentStore and return its CID
	// (ADR-0048 D4/R7). Used by an agent's working memory to offload a large block
	// and carry a {gist + cid} pointer; the blob is owner-stamped with the caller's
	// session so reads are gated (GetContextNode). Idempotent (content-addressed).
	PutContextNode(context.Context, *PutContextNodeRequest) (*PutContextNodeResponse, error)
	// WatchConfig CRUD — premium build only. ADR-0032.
	// Create or replace a reactive rule. Returns the persisted config ID.
	RegisterWatch(context.Context, *RegisterWatchRequest) (*RegisterWatchResponse, error)
	// List all registered WatchConfigs.
	ListWatches(context.Context, *ListWatchesRequest) (*ListWatchesResponse, error)
	// Delete a WatchConfig by ID.
	DeleteWatch(context.Context, *DeleteWatchRequest) (*DeleteWatchResponse, error)
	// Enable or disable a WatchConfig without deleting it.
	SetWatchActive(context.Context, *SetWatchActiveRequest) (*SetWatchActiveResponse, error)
	// Artifact storage with ADR-0034 tag-based access scoping. REQ-SDK-007c.
	// Upload validates classification tags against the writer's scope + controlled
	// vocabulary and kernel-stamps provenance before persisting.
	UploadArtifact(context.Context, *UploadArtifactRequest) (*UploadArtifactResponse, error)
	// Get an artifact by content hash; returns empty when the caller's effective
	// scope does not permit the artifact's tags (fail-closed).
	GetArtifact(context.Context, *GetArtifactRequest) (*GetArtifactResponse, error)
	// List artifacts produced by a session+step, scope-filtered for the caller.
	ListStepArtifacts(context.Context, *ListStepArtifactsRequest) (*ListStepArtifactsResponse, error)
	// memory.remember() write-back. The kernel DERIVES classification from the
	// agent's DefaultWriteTags (ADR-0035 C2); req.tags is a narrow-only hint.
	IngestMemory(context.Context, *IngestMemoryRequest) (*IngestMemoryResponse, error)
	// ADR-0039: kernel-owned tool registry. A cognitive agent invokes a granted
	// system tool with LLM-marshalled args; the kernel authorizes (grant +
	// resource policy + data scope + approval) and runs it in a confined process.
	// The principal is taken from x-agent-id gRPC metadata, never from the body.
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	// ADR-0039: the system tools the calling agent (x-agent-id) may invoke, for
	// building the agent's closed ReAct tool menu. Advisory only — ExecuteTool
	// still authorizes every call. Honors the unrestricted bypass.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// ADR-0046: the system skills the calling agent (x-agent-id) may load, for the
	// agent's [skills] menu section. Tier-1 (summary) by default; Tier-2 (full
	// instructions) for a named skill via use_skill. Scope-gated; agent-local
	// skills are NOT served here (they are SDK-local, the @tools analog).
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// ADR-0041: embed text into a vector using the kernel's embedder, for the
	// agent's Local Recurrent Workspace relevance ranking. Read-only; no auth impact.
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Operator-plane: stream pending dangerous-tool approval requests (ADR-0039 D10).
	WatchApprovals(*WatchApprovalsRequest, grpc.ServerStreamingServer[ApprovalRequest]) error
	// Operator-plane: submit an approve/deny decision for a pending request.
	SubmitApprovalDecision(context.Context, *ApprovalDecisionRequest) (*ApprovalDecisionResponse, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) Execute(context.Context, *Handoff) (*Handoff, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedOrchestratorServer) RequestProposal(context.Context, *AuctionTask) (*AgentProposal, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestProposal not implemented")
}
func (UnimplementedOrchestratorServer) QueryMemory(context.Context, *MemoryRequest) (*MemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMemory not implemented")
}
func (UnimplementedOrchestratorServer) ChatStream(grpc.BidiStreamingServer[Handoff, SymbiosisEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedOrchestratorServer) SignalStream(grpc.BidiStreamingServer[Handoff, SymbiosisEvent]) error {
	return status.Error(codes.Unimplemented, "method SignalStream not implemented")
}
func (UnimplementedOrchestratorServer) GenerateViaModelStream(*GenerateStreamRequest, grpc.ServerStreamingServer[GenerateChunk]) error {
	return status.Error(codes.Unimplemented, "method GenerateViaModelStream not implemented")
}
func (UnimplementedOrchestratorServer) GetContextNode(context.Context, *ContextNodeRequest) (*ContextNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContextNode not implemented")
}
func (UnimplementedOrchestratorServer) PutContextNode(context.Context, *PutContextNodeRequest) (*PutContextNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutContextNode not implemented")
}
func (UnimplementedOrchestratorServer) RegisterWatch(context.Context, *RegisterWatchRequest) (*RegisterWatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWatch not implemented")
}
func (UnimplementedOrchestratorServer) ListWatches(context.Context, *ListWatchesRequest) (*ListWatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatches not implemented")
}
func (UnimplementedOrchestratorServer) DeleteWatch(context.Context, *DeleteWatchRequest) (*DeleteWatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWatch not implemented")
}
func (UnimplementedOrchestratorServer) SetWatchActive(context.Context, *SetWatchActiveRequest) (*SetWatchActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWatchActive not implemented")
}
func (UnimplementedOrchestratorServer) UploadArtifact(context.Context, *UploadArtifactRequest) (*UploadArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadArtifact not implemented")
}
func (UnimplementedOrchestratorServer) GetArtifact(context.Context, *GetArtifactRequest) (*GetArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifact not implemented")
}
func (UnimplementedOrchestratorServer) ListStepArtifacts(context.Context, *ListStepArtifactsRequest) (*ListStepArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStepArtifacts not implemented")
}
func (UnimplementedOrchestratorServer) IngestMemory(context.Context, *IngestMemoryRequest) (*IngestMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMemory not implemented")
}
func (UnimplementedOrchestratorServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedOrchestratorServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedOrchestratorServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedOrchestratorServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedOrchestratorServer) WatchApprovals(*WatchApprovalsRequest, grpc.ServerStreamingServer[ApprovalRequest]) error {
	return status.Error(codes.Unimplemented, "method WatchApprovals not implemented")
}
func (UnimplementedOrchestratorServer) SubmitApprovalDecision(context.Context, *ApprovalDecisionRequest) (*ApprovalDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitApprovalDecision not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handoff)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).Execute(ctx, req.(*Handoff))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_RequestProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).RequestProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_RequestProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).RequestProposal(ctx, req.(*AuctionTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_QueryMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).QueryMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_QueryMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).QueryMemory(ctx, req.(*MemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorServer).ChatStream(&grpc.GenericServerStream[Handoff, SymbiosisEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_ChatStreamServer = grpc.BidiStreamingServer[Handoff, SymbiosisEvent]

func _Orchestrator_SignalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorServer).SignalStream(&grpc.GenericServerStream[Handoff, SymbiosisEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_SignalStreamServer = grpc.BidiStreamingServer[Handoff, SymbiosisEvent]

func _Orchestrator_GenerateViaModelStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).GenerateViaModelStream(m, &grpc.GenericServerStream[GenerateStreamRequest, GenerateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_GenerateViaModelStreamServer = grpc.ServerStreamingServer[GenerateChunk]

func _Orchestrator_GetContextNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetContextNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetContextNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetContextNode(ctx, req.(*ContextNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_PutContextNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutContextNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).PutContextNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_PutContextNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).PutContextNode(ctx, req.(*PutContextNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_RegisterWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).RegisterWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_RegisterWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).RegisterWatch(ctx, req.(*RegisterWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ListWatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListWatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListWatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListWatches(ctx, req.(*ListWatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DeleteWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DeleteWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DeleteWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DeleteWatch(ctx, req.(*DeleteWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_SetWatchActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWatchActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).SetWatchActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_SetWatchActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).SetWatchActive(ctx, req.(*SetWatchActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_UploadArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).UploadArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_UploadArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).UploadArtifact(ctx, req.(*UploadArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ListStepArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStepArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListStepArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListStepArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListStepArtifacts(ctx, req.(*ListStepArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_IngestMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).IngestMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_IngestMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).IngestMemory(ctx, req.(*IngestMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_WatchApprovals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchApprovalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).WatchApprovals(m, &grpc.GenericServerStream[WatchApprovalsRequest, ApprovalRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_WatchApprovalsServer = grpc.ServerStreamingServer[ApprovalRequest]

func _Orchestrator_SubmitApprovalDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).SubmitApprovalDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_SubmitApprovalDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).SubmitApprovalDecision(ctx, req.(*ApprovalDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cambrian.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Orchestrator_Execute_Handler,
		},
		{
			MethodName: "RequestProposal",
			Handler:    _Orchestrator_RequestProposal_Handler,
		},
		{
			MethodName: "QueryMemory",
			Handler:    _Orchestrator_QueryMemory_Handler,
		},
		{
			MethodName: "GetContextNode",
			Handler:    _Orchestrator_GetContextNode_Handler,
		},
		{
			MethodName: "PutContextNode",
			Handler:    _Orchestrator_PutContextNode_Handler,
		},
		{
			MethodName: "RegisterWatch",
			Handler:    _Orchestrator_RegisterWatch_Handler,
		},
		{
			MethodName: "ListWatches",
			Handler:    _Orchestrator_ListWatches_Handler,
		},
		{
			MethodName: "DeleteWatch",
			Handler:    _Orchestrator_DeleteWatch_Handler,
		},
		{
			MethodName: "SetWatchActive",
			Handler:    _Orchestrator_SetWatchActive_Handler,
		},
		{
			MethodName: "UploadArtifact",
			Handler:    _Orchestrator_UploadArtifact_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _Orchestrator_GetArtifact_Handler,
		},
		{
			MethodName: "ListStepArtifacts",
			Handler:    _Orchestrator_ListStepArtifacts_Handler,
		},
		{
			MethodName: "IngestMemory",
			Handler:    _Orchestrator_IngestMemory_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _Orchestrator_ExecuteTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _Orchestrator_ListTools_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _Orchestrator_ListSkills_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _Orchestrator_Embed_Handler,
		},
		{
			MethodName: "SubmitApprovalDecision",
			Handler:    _Orchestrator_SubmitApprovalDecision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _Orchestrator_ChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SignalStream",
			Handler:       _Orchestrator_SignalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GenerateViaModelStream",
			Handler:       _Orchestrator_GenerateViaModelStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchApprovals",
			Handler:       _Orchestrator_WatchApprovals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cambrian.proto",
}

const (
	AgentService_RequestProposal_FullMethodName = "/cambrian.AgentService/RequestProposal"
	AgentService_Execute_FullMethodName         = "/cambrian.AgentService/Execute"
	AgentService_VerifyOutput_FullMethodName    = "/cambrian.AgentService/VerifyOutput"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service that agents register with, or that agents implement (AgentService)
type AgentServiceClient interface {
	RequestProposal(ctx context.Context, in *ProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	Execute(ctx context.Context, in *Handoff, opts ...grpc.CallOption) (*Handoff, error)
	VerifyOutput(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RequestProposal(ctx context.Context, in *ProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, AgentService_RequestProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Execute(ctx context.Context, in *Handoff, opts ...grpc.CallOption) (*Handoff, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Handoff)
	err := c.cc.Invoke(ctx, AgentService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) VerifyOutput(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, AgentService_VerifyOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// Service that agents register with, or that agents implement (AgentService)
type AgentServiceServer interface {
	RequestProposal(context.Context, *ProposalRequest) (*ProposalResponse, error)
	Execute(context.Context, *Handoff) (*Handoff, error)
	VerifyOutput(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RequestProposal(context.Context, *ProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestProposal not implemented")
}
func (UnimplementedAgentServiceServer) Execute(context.Context, *Handoff) (*Handoff, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAgentServiceServer) VerifyOutput(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOutput not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RequestProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RequestProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RequestProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RequestProposal(ctx, req.(*ProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handoff)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Execute(ctx, req.(*Handoff))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_VerifyOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).VerifyOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_VerifyOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).VerifyOutput(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cambrian.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestProposal",
			Handler:    _AgentService_RequestProposal_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _AgentService_Execute_Handler,
		},
		{
			MethodName: "VerifyOutput",
			Handler:    _AgentService_VerifyOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cambrian.proto",
}
