// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: operator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperatorConsole_Login_FullMethodName                = "/cambrian.OperatorConsole/Login"
	OperatorConsole_StreamEvents_FullMethodName         = "/cambrian.OperatorConsole/StreamEvents"
	OperatorConsole_Snapshot_FullMethodName             = "/cambrian.OperatorConsole/Snapshot"
	OperatorConsole_SetToolGrant_FullMethodName         = "/cambrian.OperatorConsole/SetToolGrant"
	OperatorConsole_QueryAudit_FullMethodName           = "/cambrian.OperatorConsole/QueryAudit"
	OperatorConsole_ResolveHITL_FullMethodName          = "/cambrian.OperatorConsole/ResolveHITL"
	OperatorConsole_PauseSession_FullMethodName         = "/cambrian.OperatorConsole/PauseSession"
	OperatorConsole_ResumeSession_FullMethodName        = "/cambrian.OperatorConsole/ResumeSession"
	OperatorConsole_TagMemory_FullMethodName            = "/cambrian.OperatorConsole/TagMemory"
	OperatorConsole_SetScope_FullMethodName             = "/cambrian.OperatorConsole/SetScope"
	OperatorConsole_RegisterSkill_FullMethodName        = "/cambrian.OperatorConsole/RegisterSkill"
	OperatorConsole_RegisterMCP_FullMethodName          = "/cambrian.OperatorConsole/RegisterMCP"
	OperatorConsole_TriggerConsolidation_FullMethodName = "/cambrian.OperatorConsole/TriggerConsolidation"
	OperatorConsole_SetRuntimeConfig_FullMethodName     = "/cambrian.OperatorConsole/SetRuntimeConfig"
	OperatorConsole_CreateSession_FullMethodName        = "/cambrian.OperatorConsole/CreateSession"
	OperatorConsole_SendMessage_FullMethodName          = "/cambrian.OperatorConsole/SendMessage"
	OperatorConsole_InjectCorrection_FullMethodName     = "/cambrian.OperatorConsole/InjectCorrection"
)

// OperatorConsoleClient is the client API for OperatorConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperatorConsole is the operator-plane service for the Cambrian UI (ADR-0047).
// It is distinct from the agent-facing Orchestrator/AgentService: its audience
// is a human Operator/Viewer, not an agent (no x-agent-id principal). This file
// holds the sequenced event feed (issue 0047-01); snapshots, commands, and auth
// are added by later slices.
type OperatorConsoleClient interface {
	// Login authenticates a human operator (username/password) and returns a
	// token bound to {principal, role}. The only unauthenticated RPC. ADR-0047 D13.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// StreamEvents drains the sequenced operator feed. The client resumes from
	// last_seq; every OperatorEvent carries a global monotonic seq (the cursor).
	StreamEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperatorEvent], error)
	// Snapshot returns bounded live operational state (plans in flight, sessions)
	// stamped with a lower-bound as_of_seq. The client resumes StreamEvents from
	// as_of_seq+1; idempotent absolute-state events make the overlap harmless.
	// Large/historical data is NOT here — paged read RPCs serve it. ADR-0047 D6/D8.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// SetToolGrant grants or revokes a system tool for an agent (Operator-only).
	// Idempotent (command_id), mandatory reason, audited. ADR-0047 D7/D15.
	SetToolGrant(ctx context.Context, in *SetToolGrantRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// QueryAudit reads the operator_audit log, filtered + paginated. Read RPC
	// (any authenticated role). Never folded into Snapshot. ADR-0047 D8/0047-08.
	QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error)
	// ResolveHITL approves/rejects a raised HITL intervention (Operator-only).
	// Idempotent on the intervention id via command_id. ADR-0047 D11/0047-09.
	ResolveHITL(ctx context.Context, in *ResolveHITLRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// PauseSession / ResumeSession steer a live execution via the control hub.
	PauseSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error)
	ResumeSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// Remaining mutations (Operator-only, idempotent, audited). ADR-0047 0047-07.
	TagMemory(ctx context.Context, in *TagMemoryRequest, opts ...grpc.CallOption) (*CommandAck, error)
	SetScope(ctx context.Context, in *SetScopeRequest, opts ...grpc.CallOption) (*CommandAck, error)
	RegisterSkill(ctx context.Context, in *RegisterSkillRequest, opts ...grpc.CallOption) (*CommandAck, error)
	RegisterMCP(ctx context.Context, in *RegisterMCPRequest, opts ...grpc.CallOption) (*CommandAck, error)
	TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// SetRuntimeConfig hot-applies numeric runtime tunables (e.g. the Stage-A blend
	// weights) to the live kernel WITHOUT a restart — the automated-tuning seam
	// (ADR-0054). Idempotent (command_id), mandatory reason, audited, Operator-only.
	// Ephemeral: edits live in memory; config.json stays the boot default.
	SetRuntimeConfig(ctx context.Context, in *SetRuntimeConfigRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// Chat & steer (Operator-only, audited). ADR-0047 0047-10.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*CommandAck, error)
	InjectCorrection(ctx context.Context, in *InjectCorrectionRequest, opts ...grpc.CallOption) (*CommandAck, error)
}

type operatorConsoleClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorConsoleClient(cc grpc.ClientConnInterface) OperatorConsoleClient {
	return &operatorConsoleClient{cc}
}

func (c *operatorConsoleClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) StreamEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperatorEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorConsole_ServiceDesc.Streams[0], OperatorConsole_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, OperatorEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_StreamEventsClient = grpc.ServerStreamingClient[OperatorEvent]

func (c *operatorConsoleClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetToolGrant(ctx context.Context, in *SetToolGrantRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetToolGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAuditResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_QueryAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ResolveHITL(ctx context.Context, in *ResolveHITLRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_ResolveHITL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) PauseSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_PauseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ResumeSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_ResumeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) TagMemory(ctx context.Context, in *TagMemoryRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_TagMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetScope(ctx context.Context, in *SetScopeRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) RegisterSkill(ctx context.Context, in *RegisterSkillRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_RegisterSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) RegisterMCP(ctx context.Context, in *RegisterMCPRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_RegisterMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_TriggerConsolidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetRuntimeConfig(ctx context.Context, in *SetRuntimeConfigRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) InjectCorrection(ctx context.Context, in *InjectCorrectionRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_InjectCorrection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorConsoleServer is the server API for OperatorConsole service.
// All implementations must embed UnimplementedOperatorConsoleServer
// for forward compatibility.
//
// OperatorConsole is the operator-plane service for the Cambrian UI (ADR-0047).
// It is distinct from the agent-facing Orchestrator/AgentService: its audience
// is a human Operator/Viewer, not an agent (no x-agent-id principal). This file
// holds the sequenced event feed (issue 0047-01); snapshots, commands, and auth
// are added by later slices.
type OperatorConsoleServer interface {
	// Login authenticates a human operator (username/password) and returns a
	// token bound to {principal, role}. The only unauthenticated RPC. ADR-0047 D13.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// StreamEvents drains the sequenced operator feed. The client resumes from
	// last_seq; every OperatorEvent carries a global monotonic seq (the cursor).
	StreamEvents(*SubscribeRequest, grpc.ServerStreamingServer[OperatorEvent]) error
	// Snapshot returns bounded live operational state (plans in flight, sessions)
	// stamped with a lower-bound as_of_seq. The client resumes StreamEvents from
	// as_of_seq+1; idempotent absolute-state events make the overlap harmless.
	// Large/historical data is NOT here — paged read RPCs serve it. ADR-0047 D6/D8.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// SetToolGrant grants or revokes a system tool for an agent (Operator-only).
	// Idempotent (command_id), mandatory reason, audited. ADR-0047 D7/D15.
	SetToolGrant(context.Context, *SetToolGrantRequest) (*CommandAck, error)
	// QueryAudit reads the operator_audit log, filtered + paginated. Read RPC
	// (any authenticated role). Never folded into Snapshot. ADR-0047 D8/0047-08.
	QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error)
	// ResolveHITL approves/rejects a raised HITL intervention (Operator-only).
	// Idempotent on the intervention id via command_id. ADR-0047 D11/0047-09.
	ResolveHITL(context.Context, *ResolveHITLRequest) (*CommandAck, error)
	// PauseSession / ResumeSession steer a live execution via the control hub.
	PauseSession(context.Context, *SessionCommandRequest) (*CommandAck, error)
	ResumeSession(context.Context, *SessionCommandRequest) (*CommandAck, error)
	// Remaining mutations (Operator-only, idempotent, audited). ADR-0047 0047-07.
	TagMemory(context.Context, *TagMemoryRequest) (*CommandAck, error)
	SetScope(context.Context, *SetScopeRequest) (*CommandAck, error)
	RegisterSkill(context.Context, *RegisterSkillRequest) (*CommandAck, error)
	RegisterMCP(context.Context, *RegisterMCPRequest) (*CommandAck, error)
	TriggerConsolidation(context.Context, *TriggerConsolidationRequest) (*CommandAck, error)
	// SetRuntimeConfig hot-applies numeric runtime tunables (e.g. the Stage-A blend
	// weights) to the live kernel WITHOUT a restart — the automated-tuning seam
	// (ADR-0054). Idempotent (command_id), mandatory reason, audited, Operator-only.
	// Ephemeral: edits live in memory; config.json stays the boot default.
	SetRuntimeConfig(context.Context, *SetRuntimeConfigRequest) (*CommandAck, error)
	// Chat & steer (Operator-only, audited). ADR-0047 0047-10.
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*CommandAck, error)
	InjectCorrection(context.Context, *InjectCorrectionRequest) (*CommandAck, error)
	mustEmbedUnimplementedOperatorConsoleServer()
}

// UnimplementedOperatorConsoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorConsoleServer struct{}

func (UnimplementedOperatorConsoleServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedOperatorConsoleServer) StreamEvents(*SubscribeRequest, grpc.ServerStreamingServer[OperatorEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedOperatorConsoleServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedOperatorConsoleServer) SetToolGrant(context.Context, *SetToolGrantRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetToolGrant not implemented")
}
func (UnimplementedOperatorConsoleServer) QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAudit not implemented")
}
func (UnimplementedOperatorConsoleServer) ResolveHITL(context.Context, *ResolveHITLRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveHITL not implemented")
}
func (UnimplementedOperatorConsoleServer) PauseSession(context.Context, *SessionCommandRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSession not implemented")
}
func (UnimplementedOperatorConsoleServer) ResumeSession(context.Context, *SessionCommandRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedOperatorConsoleServer) TagMemory(context.Context, *TagMemoryRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method TagMemory not implemented")
}
func (UnimplementedOperatorConsoleServer) SetScope(context.Context, *SetScopeRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetScope not implemented")
}
func (UnimplementedOperatorConsoleServer) RegisterSkill(context.Context, *RegisterSkillRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSkill not implemented")
}
func (UnimplementedOperatorConsoleServer) RegisterMCP(context.Context, *RegisterMCPRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMCP not implemented")
}
func (UnimplementedOperatorConsoleServer) TriggerConsolidation(context.Context, *TriggerConsolidationRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerConsolidation not implemented")
}
func (UnimplementedOperatorConsoleServer) SetRuntimeConfig(context.Context, *SetRuntimeConfigRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRuntimeConfig not implemented")
}
func (UnimplementedOperatorConsoleServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedOperatorConsoleServer) SendMessage(context.Context, *SendMessageRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedOperatorConsoleServer) InjectCorrection(context.Context, *InjectCorrectionRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectCorrection not implemented")
}
func (UnimplementedOperatorConsoleServer) mustEmbedUnimplementedOperatorConsoleServer() {}
func (UnimplementedOperatorConsoleServer) testEmbeddedByValue()                         {}

// UnsafeOperatorConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorConsoleServer will
// result in compilation errors.
type UnsafeOperatorConsoleServer interface {
	mustEmbedUnimplementedOperatorConsoleServer()
}

func RegisterOperatorConsoleServer(s grpc.ServiceRegistrar, srv OperatorConsoleServer) {
	// If the following call panics, it indicates UnimplementedOperatorConsoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorConsole_ServiceDesc, srv)
}

func _OperatorConsole_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorConsoleServer).StreamEvents(m, &grpc.GenericServerStream[SubscribeRequest, OperatorEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_StreamEventsServer = grpc.ServerStreamingServer[OperatorEvent]

func _OperatorConsole_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetToolGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetToolGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetToolGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetToolGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetToolGrant(ctx, req.(*SetToolGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_QueryAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).QueryAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_QueryAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).QueryAudit(ctx, req.(*QueryAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ResolveHITL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHITLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ResolveHITL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ResolveHITL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ResolveHITL(ctx, req.(*ResolveHITLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_PauseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).PauseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_PauseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).PauseSession(ctx, req.(*SessionCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ResumeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ResumeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ResumeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ResumeSession(ctx, req.(*SessionCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_TagMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).TagMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_TagMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).TagMemory(ctx, req.(*TagMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetScope(ctx, req.(*SetScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_RegisterSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).RegisterSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_RegisterSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).RegisterSkill(ctx, req.(*RegisterSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_RegisterMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).RegisterMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_RegisterMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).RegisterMCP(ctx, req.(*RegisterMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_TriggerConsolidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerConsolidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).TriggerConsolidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_TriggerConsolidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).TriggerConsolidation(ctx, req.(*TriggerConsolidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetRuntimeConfig(ctx, req.(*SetRuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_InjectCorrection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectCorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).InjectCorrection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_InjectCorrection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).InjectCorrection(ctx, req.(*InjectCorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorConsole_ServiceDesc is the grpc.ServiceDesc for OperatorConsole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorConsole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cambrian.OperatorConsole",
	HandlerType: (*OperatorConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _OperatorConsole_Login_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _OperatorConsole_Snapshot_Handler,
		},
		{
			MethodName: "SetToolGrant",
			Handler:    _OperatorConsole_SetToolGrant_Handler,
		},
		{
			MethodName: "QueryAudit",
			Handler:    _OperatorConsole_QueryAudit_Handler,
		},
		{
			MethodName: "ResolveHITL",
			Handler:    _OperatorConsole_ResolveHITL_Handler,
		},
		{
			MethodName: "PauseSession",
			Handler:    _OperatorConsole_PauseSession_Handler,
		},
		{
			MethodName: "ResumeSession",
			Handler:    _OperatorConsole_ResumeSession_Handler,
		},
		{
			MethodName: "TagMemory",
			Handler:    _OperatorConsole_TagMemory_Handler,
		},
		{
			MethodName: "SetScope",
			Handler:    _OperatorConsole_SetScope_Handler,
		},
		{
			MethodName: "RegisterSkill",
			Handler:    _OperatorConsole_RegisterSkill_Handler,
		},
		{
			MethodName: "RegisterMCP",
			Handler:    _OperatorConsole_RegisterMCP_Handler,
		},
		{
			MethodName: "TriggerConsolidation",
			Handler:    _OperatorConsole_TriggerConsolidation_Handler,
		},
		{
			MethodName: "SetRuntimeConfig",
			Handler:    _OperatorConsole_SetRuntimeConfig_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _OperatorConsole_CreateSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _OperatorConsole_SendMessage_Handler,
		},
		{
			MethodName: "InjectCorrection",
			Handler:    _OperatorConsole_InjectCorrection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _OperatorConsole_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "operator.proto",
}
