// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: operator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperatorConsole_Login_FullMethodName                = "/cambrian.OperatorConsole/Login"
	OperatorConsole_StreamEvents_FullMethodName         = "/cambrian.OperatorConsole/StreamEvents"
	OperatorConsole_Snapshot_FullMethodName             = "/cambrian.OperatorConsole/Snapshot"
	OperatorConsole_SetToolGrant_FullMethodName         = "/cambrian.OperatorConsole/SetToolGrant"
	OperatorConsole_QueryAudit_FullMethodName           = "/cambrian.OperatorConsole/QueryAudit"
	OperatorConsole_ResolveHITL_FullMethodName          = "/cambrian.OperatorConsole/ResolveHITL"
	OperatorConsole_PauseSession_FullMethodName         = "/cambrian.OperatorConsole/PauseSession"
	OperatorConsole_ResumeSession_FullMethodName        = "/cambrian.OperatorConsole/ResumeSession"
	OperatorConsole_TagMemory_FullMethodName            = "/cambrian.OperatorConsole/TagMemory"
	OperatorConsole_SetScope_FullMethodName             = "/cambrian.OperatorConsole/SetScope"
	OperatorConsole_RegisterSkill_FullMethodName        = "/cambrian.OperatorConsole/RegisterSkill"
	OperatorConsole_RegisterMCP_FullMethodName          = "/cambrian.OperatorConsole/RegisterMCP"
	OperatorConsole_TriggerConsolidation_FullMethodName = "/cambrian.OperatorConsole/TriggerConsolidation"
	OperatorConsole_SetRuntimeConfig_FullMethodName     = "/cambrian.OperatorConsole/SetRuntimeConfig"
	OperatorConsole_CreateSession_FullMethodName        = "/cambrian.OperatorConsole/CreateSession"
	OperatorConsole_SendMessage_FullMethodName          = "/cambrian.OperatorConsole/SendMessage"
	OperatorConsole_InjectCorrection_FullMethodName     = "/cambrian.OperatorConsole/InjectCorrection"
	OperatorConsole_ListTools_FullMethodName            = "/cambrian.OperatorConsole/ListTools"
	OperatorConsole_ListSkills_FullMethodName           = "/cambrian.OperatorConsole/ListSkills"
	OperatorConsole_QueryMemory_FullMethodName          = "/cambrian.OperatorConsole/QueryMemory"
	OperatorConsole_AnswerMemory_FullMethodName         = "/cambrian.OperatorConsole/AnswerMemory"
	OperatorConsole_SetToolPolicy_FullMethodName        = "/cambrian.OperatorConsole/SetToolPolicy"
	OperatorConsole_ExecuteTool_FullMethodName          = "/cambrian.OperatorConsole/ExecuteTool"
	OperatorConsole_IngestMemory_FullMethodName         = "/cambrian.OperatorConsole/IngestMemory"
	OperatorConsole_WatchToolApprovals_FullMethodName   = "/cambrian.OperatorConsole/WatchToolApprovals"
	OperatorConsole_ListWatches_FullMethodName          = "/cambrian.OperatorConsole/ListWatches"
	OperatorConsole_RegisterWatch_FullMethodName        = "/cambrian.OperatorConsole/RegisterWatch"
	OperatorConsole_DeleteWatch_FullMethodName          = "/cambrian.OperatorConsole/DeleteWatch"
	OperatorConsole_SetWatchActive_FullMethodName       = "/cambrian.OperatorConsole/SetWatchActive"
	OperatorConsole_ListWatchDeadLetters_FullMethodName = "/cambrian.OperatorConsole/ListWatchDeadLetters"
	OperatorConsole_GetWatchMetrics_FullMethodName      = "/cambrian.OperatorConsole/GetWatchMetrics"
	OperatorConsole_BacktestWatch_FullMethodName        = "/cambrian.OperatorConsole/BacktestWatch"
	OperatorConsole_PreviewRoute_FullMethodName         = "/cambrian.OperatorConsole/PreviewRoute"
)

// OperatorConsoleClient is the client API for OperatorConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperatorConsole is the operator-plane service for the Cambrian UI (ADR-0047).
// It is distinct from the agent-facing Orchestrator/AgentService: its audience
// is a human Operator/Viewer, not an agent (no x-agent-id principal). This file
// holds the sequenced event feed (issue 0047-01); snapshots, commands, and auth
// are added by later slices.
type OperatorConsoleClient interface {
	// Login authenticates a human operator (username/password) and returns a
	// token bound to {principal, role}. The only unauthenticated RPC. ADR-0047 D13.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// StreamEvents drains the sequenced operator feed. The client resumes from
	// last_seq; every OperatorEvent carries a global monotonic seq (the cursor).
	StreamEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperatorEvent], error)
	// Snapshot returns bounded live operational state (plans in flight, sessions)
	// stamped with a lower-bound as_of_seq. The client resumes StreamEvents from
	// as_of_seq+1; idempotent absolute-state events make the overlap harmless.
	// Large/historical data is NOT here — paged read RPCs serve it. ADR-0047 D6/D8.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// SetToolGrant grants or revokes a system tool for an agent (Operator-only).
	// Idempotent (command_id), mandatory reason, audited. ADR-0047 D7/D15.
	SetToolGrant(ctx context.Context, in *SetToolGrantRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// QueryAudit reads the operator_audit log, filtered + paginated. Read RPC
	// (any authenticated role). Never folded into Snapshot. ADR-0047 D8/0047-08.
	QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error)
	// ResolveHITL approves/rejects a raised HITL intervention (Operator-only).
	// Idempotent on the intervention id via command_id. ADR-0047 D11/0047-09.
	ResolveHITL(ctx context.Context, in *ResolveHITLRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// PauseSession / ResumeSession steer a live execution via the control hub.
	PauseSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error)
	ResumeSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// Remaining mutations (Operator-only, idempotent, audited). ADR-0047 0047-07.
	TagMemory(ctx context.Context, in *TagMemoryRequest, opts ...grpc.CallOption) (*CommandAck, error)
	SetScope(ctx context.Context, in *SetScopeRequest, opts ...grpc.CallOption) (*CommandAck, error)
	RegisterSkill(ctx context.Context, in *RegisterSkillRequest, opts ...grpc.CallOption) (*CommandAck, error)
	RegisterMCP(ctx context.Context, in *RegisterMCPRequest, opts ...grpc.CallOption) (*CommandAck, error)
	TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// SetRuntimeConfig hot-applies numeric runtime tunables (e.g. the Stage-A blend
	// weights) to the live kernel WITHOUT a restart — the automated-tuning seam
	// (ADR-0054). Idempotent (command_id), mandatory reason, audited, Operator-only.
	// Ephemeral: edits live in memory; config.json stays the boot default.
	SetRuntimeConfig(ctx context.Context, in *SetRuntimeConfigRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// Chat & steer (Operator-only, audited). ADR-0047 0047-10.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*CommandAck, error)
	InjectCorrection(ctx context.Context, in *InjectCorrectionRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// Paged reads (any authenticated role; never folded into Snapshot). A2.1/D8.
	ListTools(ctx context.Context, in *ListToolsOpRequest, opts ...grpc.CallOption) (*ListToolsOpResponse, error)
	ListSkills(ctx context.Context, in *ListSkillsOpRequest, opts ...grpc.CallOption) (*ListSkillsOpResponse, error)
	QueryMemory(ctx context.Context, in *QueryMemoryRequest, opts ...grpc.CallOption) (*QueryMemoryResponse, error)
	// AnswerMemory (ADR-0081) runs the agentic retrieval loop and returns a GROUNDED
	// composed answer with inline [n] citation markers, plus the evidence each marker
	// resolves to. Distinct from QueryMemory's single-pass evidence lane: this is a
	// read that synthesizes (no auction, no mutation, no x-agent-id principal). Gated
	// on the "memory-answer" capability; OSS / agentic-disabled builds return
	// Unimplemented.
	AnswerMemory(ctx context.Context, in *AnswerMemoryRequest, opts ...grpc.CallOption) (*AnswerMemoryResponse, error)
	// Tool permission management: bound an existing grant with a resource policy
	// (Operator-only, idempotent, audited). A2.3.
	SetToolPolicy(ctx context.Context, in *SetToolPolicyRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// Operator-triggered tool execution at ScopeSystem — a deliberate grant
	// bypass, audited, dangerous tools also emit a feed event (Operator-only). A2.2.
	ExecuteTool(ctx context.Context, in *ExecuteToolOpRequest, opts ...grpc.CallOption) (*ExecuteToolOpResponse, error)
	// Memory ingest through the kernel ingest path (operator as Author; never a
	// raw store write). Idempotent on command_id (Operator-only, audited). A2.4.
	IngestMemory(ctx context.Context, in *IngestMemoryOpRequest, opts ...grpc.CallOption) (*IngestMemoryOpResponse, error)
	// Tool-approval stream mirroring the ADR-0039 dangerous-tool approval request
	// (Operator-only). Resolve reuses ResolveHITL over the shared ApprovalHub
	// id-space. A2.5.
	WatchToolApprovals(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApprovalOp], error)
	// ── Watch surfaces — PREMIUM capability-gated (D14/A2.6). The proto lives in
	// OSS in full (defining ≠ implementing); OSS handlers return Unimplemented and
	// the WatchTriggered class never publishes. Advertised only on premium builds.
	ListWatches(ctx context.Context, in *ListWatchesOpRequest, opts ...grpc.CallOption) (*ListWatchesOpResponse, error)
	RegisterWatch(ctx context.Context, in *RegisterWatchOpRequest, opts ...grpc.CallOption) (*CommandAck, error)
	DeleteWatch(ctx context.Context, in *DeleteWatchOpRequest, opts ...grpc.CallOption) (*CommandAck, error)
	SetWatchActive(ctx context.Context, in *SetWatchActiveOpRequest, opts ...grpc.CallOption) (*CommandAck, error)
	// ListWatchDeadLetters reads reactive actions that could not be delivered — a
	// failed action or a journal signal that expired before it ran (REACT-01 /
	// ADR-0061). Read RPC (no command_id). Capability "watch-deadletter", advertised
	// on premium builds; OSS returns an empty list (no reactive engine writes them).
	ListWatchDeadLetters(ctx context.Context, in *ListWatchDeadLettersOpRequest, opts ...grpc.CallOption) (*ListWatchDeadLettersOpResponse, error)
	// REACT-05 / ADR-0071: watch observability. GetWatchMetrics returns per-watch fire/
	// suppression/dry-run/dead-letter counters + mean condition latency. BacktestWatch
	// replays the signal journal through a candidate watch config and reports would-fires
	// WITHOUT acting. Capability "watch-observability"; premium (OSS ⇒ Unimplemented).
	GetWatchMetrics(ctx context.Context, in *GetWatchMetricsOpRequest, opts ...grpc.CallOption) (*GetWatchMetricsOpResponse, error)
	BacktestWatch(ctx context.Context, in *BacktestWatchOpRequest, opts ...grpc.CallOption) (*BacktestWatchOpResponse, error)
	// PreviewRoute (ROUTE-07 / ADR-0077) runs the Gatekeeper's L3 merit scoring over a
	// caller-supplied candidate set (inline synthetic profiles) for a step's required
	// capabilities, and returns the ranked funnel — WITHOUT the planner, an auction, or
	// agent execution. It is the gatekeeper-benchmark entry point: deterministic routing
	// data-generation + evaluation, under the active scorer arm (hand weights or the
	// ROUTE-07 learned scorer). Capability "route-preview"; nil-in-OSS ⇒ Unimplemented.
	PreviewRoute(ctx context.Context, in *PreviewRouteOpRequest, opts ...grpc.CallOption) (*PreviewRouteOpResponse, error)
}

type operatorConsoleClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorConsoleClient(cc grpc.ClientConnInterface) OperatorConsoleClient {
	return &operatorConsoleClient{cc}
}

func (c *operatorConsoleClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) StreamEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperatorEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorConsole_ServiceDesc.Streams[0], OperatorConsole_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, OperatorEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_StreamEventsClient = grpc.ServerStreamingClient[OperatorEvent]

func (c *operatorConsoleClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetToolGrant(ctx context.Context, in *SetToolGrantRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetToolGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAuditResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_QueryAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ResolveHITL(ctx context.Context, in *ResolveHITLRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_ResolveHITL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) PauseSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_PauseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ResumeSession(ctx context.Context, in *SessionCommandRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_ResumeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) TagMemory(ctx context.Context, in *TagMemoryRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_TagMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetScope(ctx context.Context, in *SetScopeRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) RegisterSkill(ctx context.Context, in *RegisterSkillRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_RegisterSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) RegisterMCP(ctx context.Context, in *RegisterMCPRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_RegisterMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_TriggerConsolidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetRuntimeConfig(ctx context.Context, in *SetRuntimeConfigRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) InjectCorrection(ctx context.Context, in *InjectCorrectionRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_InjectCorrection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ListTools(ctx context.Context, in *ListToolsOpRequest, opts ...grpc.CallOption) (*ListToolsOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ListSkills(ctx context.Context, in *ListSkillsOpRequest, opts ...grpc.CallOption) (*ListSkillsOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) QueryMemory(ctx context.Context, in *QueryMemoryRequest, opts ...grpc.CallOption) (*QueryMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMemoryResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_QueryMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) AnswerMemory(ctx context.Context, in *AnswerMemoryRequest, opts ...grpc.CallOption) (*AnswerMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerMemoryResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_AnswerMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetToolPolicy(ctx context.Context, in *SetToolPolicyRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetToolPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ExecuteTool(ctx context.Context, in *ExecuteToolOpRequest, opts ...grpc.CallOption) (*ExecuteToolOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) IngestMemory(ctx context.Context, in *IngestMemoryOpRequest, opts ...grpc.CallOption) (*IngestMemoryOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMemoryOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_IngestMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) WatchToolApprovals(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApprovalOp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorConsole_ServiceDesc.Streams[1], OperatorConsole_WatchToolApprovals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ApprovalOp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_WatchToolApprovalsClient = grpc.ServerStreamingClient[ApprovalOp]

func (c *operatorConsoleClient) ListWatches(ctx context.Context, in *ListWatchesOpRequest, opts ...grpc.CallOption) (*ListWatchesOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchesOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_ListWatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) RegisterWatch(ctx context.Context, in *RegisterWatchOpRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_RegisterWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) DeleteWatch(ctx context.Context, in *DeleteWatchOpRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_DeleteWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) SetWatchActive(ctx context.Context, in *SetWatchActiveOpRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, OperatorConsole_SetWatchActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) ListWatchDeadLetters(ctx context.Context, in *ListWatchDeadLettersOpRequest, opts ...grpc.CallOption) (*ListWatchDeadLettersOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchDeadLettersOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_ListWatchDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) GetWatchMetrics(ctx context.Context, in *GetWatchMetricsOpRequest, opts ...grpc.CallOption) (*GetWatchMetricsOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWatchMetricsOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_GetWatchMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) BacktestWatch(ctx context.Context, in *BacktestWatchOpRequest, opts ...grpc.CallOption) (*BacktestWatchOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BacktestWatchOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_BacktestWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorConsoleClient) PreviewRoute(ctx context.Context, in *PreviewRouteOpRequest, opts ...grpc.CallOption) (*PreviewRouteOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewRouteOpResponse)
	err := c.cc.Invoke(ctx, OperatorConsole_PreviewRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorConsoleServer is the server API for OperatorConsole service.
// All implementations must embed UnimplementedOperatorConsoleServer
// for forward compatibility.
//
// OperatorConsole is the operator-plane service for the Cambrian UI (ADR-0047).
// It is distinct from the agent-facing Orchestrator/AgentService: its audience
// is a human Operator/Viewer, not an agent (no x-agent-id principal). This file
// holds the sequenced event feed (issue 0047-01); snapshots, commands, and auth
// are added by later slices.
type OperatorConsoleServer interface {
	// Login authenticates a human operator (username/password) and returns a
	// token bound to {principal, role}. The only unauthenticated RPC. ADR-0047 D13.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// StreamEvents drains the sequenced operator feed. The client resumes from
	// last_seq; every OperatorEvent carries a global monotonic seq (the cursor).
	StreamEvents(*SubscribeRequest, grpc.ServerStreamingServer[OperatorEvent]) error
	// Snapshot returns bounded live operational state (plans in flight, sessions)
	// stamped with a lower-bound as_of_seq. The client resumes StreamEvents from
	// as_of_seq+1; idempotent absolute-state events make the overlap harmless.
	// Large/historical data is NOT here — paged read RPCs serve it. ADR-0047 D6/D8.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// SetToolGrant grants or revokes a system tool for an agent (Operator-only).
	// Idempotent (command_id), mandatory reason, audited. ADR-0047 D7/D15.
	SetToolGrant(context.Context, *SetToolGrantRequest) (*CommandAck, error)
	// QueryAudit reads the operator_audit log, filtered + paginated. Read RPC
	// (any authenticated role). Never folded into Snapshot. ADR-0047 D8/0047-08.
	QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error)
	// ResolveHITL approves/rejects a raised HITL intervention (Operator-only).
	// Idempotent on the intervention id via command_id. ADR-0047 D11/0047-09.
	ResolveHITL(context.Context, *ResolveHITLRequest) (*CommandAck, error)
	// PauseSession / ResumeSession steer a live execution via the control hub.
	PauseSession(context.Context, *SessionCommandRequest) (*CommandAck, error)
	ResumeSession(context.Context, *SessionCommandRequest) (*CommandAck, error)
	// Remaining mutations (Operator-only, idempotent, audited). ADR-0047 0047-07.
	TagMemory(context.Context, *TagMemoryRequest) (*CommandAck, error)
	SetScope(context.Context, *SetScopeRequest) (*CommandAck, error)
	RegisterSkill(context.Context, *RegisterSkillRequest) (*CommandAck, error)
	RegisterMCP(context.Context, *RegisterMCPRequest) (*CommandAck, error)
	TriggerConsolidation(context.Context, *TriggerConsolidationRequest) (*CommandAck, error)
	// SetRuntimeConfig hot-applies numeric runtime tunables (e.g. the Stage-A blend
	// weights) to the live kernel WITHOUT a restart — the automated-tuning seam
	// (ADR-0054). Idempotent (command_id), mandatory reason, audited, Operator-only.
	// Ephemeral: edits live in memory; config.json stays the boot default.
	SetRuntimeConfig(context.Context, *SetRuntimeConfigRequest) (*CommandAck, error)
	// Chat & steer (Operator-only, audited). ADR-0047 0047-10.
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*CommandAck, error)
	InjectCorrection(context.Context, *InjectCorrectionRequest) (*CommandAck, error)
	// Paged reads (any authenticated role; never folded into Snapshot). A2.1/D8.
	ListTools(context.Context, *ListToolsOpRequest) (*ListToolsOpResponse, error)
	ListSkills(context.Context, *ListSkillsOpRequest) (*ListSkillsOpResponse, error)
	QueryMemory(context.Context, *QueryMemoryRequest) (*QueryMemoryResponse, error)
	// AnswerMemory (ADR-0081) runs the agentic retrieval loop and returns a GROUNDED
	// composed answer with inline [n] citation markers, plus the evidence each marker
	// resolves to. Distinct from QueryMemory's single-pass evidence lane: this is a
	// read that synthesizes (no auction, no mutation, no x-agent-id principal). Gated
	// on the "memory-answer" capability; OSS / agentic-disabled builds return
	// Unimplemented.
	AnswerMemory(context.Context, *AnswerMemoryRequest) (*AnswerMemoryResponse, error)
	// Tool permission management: bound an existing grant with a resource policy
	// (Operator-only, idempotent, audited). A2.3.
	SetToolPolicy(context.Context, *SetToolPolicyRequest) (*CommandAck, error)
	// Operator-triggered tool execution at ScopeSystem — a deliberate grant
	// bypass, audited, dangerous tools also emit a feed event (Operator-only). A2.2.
	ExecuteTool(context.Context, *ExecuteToolOpRequest) (*ExecuteToolOpResponse, error)
	// Memory ingest through the kernel ingest path (operator as Author; never a
	// raw store write). Idempotent on command_id (Operator-only, audited). A2.4.
	IngestMemory(context.Context, *IngestMemoryOpRequest) (*IngestMemoryOpResponse, error)
	// Tool-approval stream mirroring the ADR-0039 dangerous-tool approval request
	// (Operator-only). Resolve reuses ResolveHITL over the shared ApprovalHub
	// id-space. A2.5.
	WatchToolApprovals(*SubscribeRequest, grpc.ServerStreamingServer[ApprovalOp]) error
	// ── Watch surfaces — PREMIUM capability-gated (D14/A2.6). The proto lives in
	// OSS in full (defining ≠ implementing); OSS handlers return Unimplemented and
	// the WatchTriggered class never publishes. Advertised only on premium builds.
	ListWatches(context.Context, *ListWatchesOpRequest) (*ListWatchesOpResponse, error)
	RegisterWatch(context.Context, *RegisterWatchOpRequest) (*CommandAck, error)
	DeleteWatch(context.Context, *DeleteWatchOpRequest) (*CommandAck, error)
	SetWatchActive(context.Context, *SetWatchActiveOpRequest) (*CommandAck, error)
	// ListWatchDeadLetters reads reactive actions that could not be delivered — a
	// failed action or a journal signal that expired before it ran (REACT-01 /
	// ADR-0061). Read RPC (no command_id). Capability "watch-deadletter", advertised
	// on premium builds; OSS returns an empty list (no reactive engine writes them).
	ListWatchDeadLetters(context.Context, *ListWatchDeadLettersOpRequest) (*ListWatchDeadLettersOpResponse, error)
	// REACT-05 / ADR-0071: watch observability. GetWatchMetrics returns per-watch fire/
	// suppression/dry-run/dead-letter counters + mean condition latency. BacktestWatch
	// replays the signal journal through a candidate watch config and reports would-fires
	// WITHOUT acting. Capability "watch-observability"; premium (OSS ⇒ Unimplemented).
	GetWatchMetrics(context.Context, *GetWatchMetricsOpRequest) (*GetWatchMetricsOpResponse, error)
	BacktestWatch(context.Context, *BacktestWatchOpRequest) (*BacktestWatchOpResponse, error)
	// PreviewRoute (ROUTE-07 / ADR-0077) runs the Gatekeeper's L3 merit scoring over a
	// caller-supplied candidate set (inline synthetic profiles) for a step's required
	// capabilities, and returns the ranked funnel — WITHOUT the planner, an auction, or
	// agent execution. It is the gatekeeper-benchmark entry point: deterministic routing
	// data-generation + evaluation, under the active scorer arm (hand weights or the
	// ROUTE-07 learned scorer). Capability "route-preview"; nil-in-OSS ⇒ Unimplemented.
	PreviewRoute(context.Context, *PreviewRouteOpRequest) (*PreviewRouteOpResponse, error)
	mustEmbedUnimplementedOperatorConsoleServer()
}

// UnimplementedOperatorConsoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorConsoleServer struct{}

func (UnimplementedOperatorConsoleServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedOperatorConsoleServer) StreamEvents(*SubscribeRequest, grpc.ServerStreamingServer[OperatorEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedOperatorConsoleServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedOperatorConsoleServer) SetToolGrant(context.Context, *SetToolGrantRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetToolGrant not implemented")
}
func (UnimplementedOperatorConsoleServer) QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAudit not implemented")
}
func (UnimplementedOperatorConsoleServer) ResolveHITL(context.Context, *ResolveHITLRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveHITL not implemented")
}
func (UnimplementedOperatorConsoleServer) PauseSession(context.Context, *SessionCommandRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSession not implemented")
}
func (UnimplementedOperatorConsoleServer) ResumeSession(context.Context, *SessionCommandRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedOperatorConsoleServer) TagMemory(context.Context, *TagMemoryRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method TagMemory not implemented")
}
func (UnimplementedOperatorConsoleServer) SetScope(context.Context, *SetScopeRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetScope not implemented")
}
func (UnimplementedOperatorConsoleServer) RegisterSkill(context.Context, *RegisterSkillRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSkill not implemented")
}
func (UnimplementedOperatorConsoleServer) RegisterMCP(context.Context, *RegisterMCPRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMCP not implemented")
}
func (UnimplementedOperatorConsoleServer) TriggerConsolidation(context.Context, *TriggerConsolidationRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerConsolidation not implemented")
}
func (UnimplementedOperatorConsoleServer) SetRuntimeConfig(context.Context, *SetRuntimeConfigRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRuntimeConfig not implemented")
}
func (UnimplementedOperatorConsoleServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedOperatorConsoleServer) SendMessage(context.Context, *SendMessageRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedOperatorConsoleServer) InjectCorrection(context.Context, *InjectCorrectionRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectCorrection not implemented")
}
func (UnimplementedOperatorConsoleServer) ListTools(context.Context, *ListToolsOpRequest) (*ListToolsOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedOperatorConsoleServer) ListSkills(context.Context, *ListSkillsOpRequest) (*ListSkillsOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedOperatorConsoleServer) QueryMemory(context.Context, *QueryMemoryRequest) (*QueryMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMemory not implemented")
}
func (UnimplementedOperatorConsoleServer) AnswerMemory(context.Context, *AnswerMemoryRequest) (*AnswerMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerMemory not implemented")
}
func (UnimplementedOperatorConsoleServer) SetToolPolicy(context.Context, *SetToolPolicyRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetToolPolicy not implemented")
}
func (UnimplementedOperatorConsoleServer) ExecuteTool(context.Context, *ExecuteToolOpRequest) (*ExecuteToolOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedOperatorConsoleServer) IngestMemory(context.Context, *IngestMemoryOpRequest) (*IngestMemoryOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMemory not implemented")
}
func (UnimplementedOperatorConsoleServer) WatchToolApprovals(*SubscribeRequest, grpc.ServerStreamingServer[ApprovalOp]) error {
	return status.Error(codes.Unimplemented, "method WatchToolApprovals not implemented")
}
func (UnimplementedOperatorConsoleServer) ListWatches(context.Context, *ListWatchesOpRequest) (*ListWatchesOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatches not implemented")
}
func (UnimplementedOperatorConsoleServer) RegisterWatch(context.Context, *RegisterWatchOpRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWatch not implemented")
}
func (UnimplementedOperatorConsoleServer) DeleteWatch(context.Context, *DeleteWatchOpRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWatch not implemented")
}
func (UnimplementedOperatorConsoleServer) SetWatchActive(context.Context, *SetWatchActiveOpRequest) (*CommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWatchActive not implemented")
}
func (UnimplementedOperatorConsoleServer) ListWatchDeadLetters(context.Context, *ListWatchDeadLettersOpRequest) (*ListWatchDeadLettersOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchDeadLetters not implemented")
}
func (UnimplementedOperatorConsoleServer) GetWatchMetrics(context.Context, *GetWatchMetricsOpRequest) (*GetWatchMetricsOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWatchMetrics not implemented")
}
func (UnimplementedOperatorConsoleServer) BacktestWatch(context.Context, *BacktestWatchOpRequest) (*BacktestWatchOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BacktestWatch not implemented")
}
func (UnimplementedOperatorConsoleServer) PreviewRoute(context.Context, *PreviewRouteOpRequest) (*PreviewRouteOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewRoute not implemented")
}
func (UnimplementedOperatorConsoleServer) mustEmbedUnimplementedOperatorConsoleServer() {}
func (UnimplementedOperatorConsoleServer) testEmbeddedByValue()                         {}

// UnsafeOperatorConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorConsoleServer will
// result in compilation errors.
type UnsafeOperatorConsoleServer interface {
	mustEmbedUnimplementedOperatorConsoleServer()
}

func RegisterOperatorConsoleServer(s grpc.ServiceRegistrar, srv OperatorConsoleServer) {
	// If the following call panics, it indicates UnimplementedOperatorConsoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorConsole_ServiceDesc, srv)
}

func _OperatorConsole_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorConsoleServer).StreamEvents(m, &grpc.GenericServerStream[SubscribeRequest, OperatorEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_StreamEventsServer = grpc.ServerStreamingServer[OperatorEvent]

func _OperatorConsole_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetToolGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetToolGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetToolGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetToolGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetToolGrant(ctx, req.(*SetToolGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_QueryAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).QueryAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_QueryAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).QueryAudit(ctx, req.(*QueryAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ResolveHITL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHITLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ResolveHITL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ResolveHITL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ResolveHITL(ctx, req.(*ResolveHITLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_PauseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).PauseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_PauseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).PauseSession(ctx, req.(*SessionCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ResumeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ResumeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ResumeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ResumeSession(ctx, req.(*SessionCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_TagMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).TagMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_TagMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).TagMemory(ctx, req.(*TagMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetScope(ctx, req.(*SetScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_RegisterSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).RegisterSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_RegisterSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).RegisterSkill(ctx, req.(*RegisterSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_RegisterMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).RegisterMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_RegisterMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).RegisterMCP(ctx, req.(*RegisterMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_TriggerConsolidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerConsolidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).TriggerConsolidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_TriggerConsolidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).TriggerConsolidation(ctx, req.(*TriggerConsolidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetRuntimeConfig(ctx, req.(*SetRuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_InjectCorrection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectCorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).InjectCorrection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_InjectCorrection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).InjectCorrection(ctx, req.(*InjectCorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ListTools(ctx, req.(*ListToolsOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ListSkills(ctx, req.(*ListSkillsOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_QueryMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).QueryMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_QueryMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).QueryMemory(ctx, req.(*QueryMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_AnswerMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).AnswerMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_AnswerMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).AnswerMemory(ctx, req.(*AnswerMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetToolPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetToolPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetToolPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetToolPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetToolPolicy(ctx, req.(*SetToolPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ExecuteTool(ctx, req.(*ExecuteToolOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_IngestMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMemoryOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).IngestMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_IngestMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).IngestMemory(ctx, req.(*IngestMemoryOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_WatchToolApprovals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorConsoleServer).WatchToolApprovals(m, &grpc.GenericServerStream[SubscribeRequest, ApprovalOp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorConsole_WatchToolApprovalsServer = grpc.ServerStreamingServer[ApprovalOp]

func _OperatorConsole_ListWatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchesOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ListWatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ListWatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ListWatches(ctx, req.(*ListWatchesOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_RegisterWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWatchOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).RegisterWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_RegisterWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).RegisterWatch(ctx, req.(*RegisterWatchOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_DeleteWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).DeleteWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_DeleteWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).DeleteWatch(ctx, req.(*DeleteWatchOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_SetWatchActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWatchActiveOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).SetWatchActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_SetWatchActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).SetWatchActive(ctx, req.(*SetWatchActiveOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_ListWatchDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchDeadLettersOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).ListWatchDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_ListWatchDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).ListWatchDeadLetters(ctx, req.(*ListWatchDeadLettersOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_GetWatchMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchMetricsOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).GetWatchMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_GetWatchMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).GetWatchMetrics(ctx, req.(*GetWatchMetricsOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_BacktestWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacktestWatchOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).BacktestWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_BacktestWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).BacktestWatch(ctx, req.(*BacktestWatchOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorConsole_PreviewRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRouteOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorConsoleServer).PreviewRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorConsole_PreviewRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorConsoleServer).PreviewRoute(ctx, req.(*PreviewRouteOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorConsole_ServiceDesc is the grpc.ServiceDesc for OperatorConsole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorConsole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cambrian.OperatorConsole",
	HandlerType: (*OperatorConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _OperatorConsole_Login_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _OperatorConsole_Snapshot_Handler,
		},
		{
			MethodName: "SetToolGrant",
			Handler:    _OperatorConsole_SetToolGrant_Handler,
		},
		{
			MethodName: "QueryAudit",
			Handler:    _OperatorConsole_QueryAudit_Handler,
		},
		{
			MethodName: "ResolveHITL",
			Handler:    _OperatorConsole_ResolveHITL_Handler,
		},
		{
			MethodName: "PauseSession",
			Handler:    _OperatorConsole_PauseSession_Handler,
		},
		{
			MethodName: "ResumeSession",
			Handler:    _OperatorConsole_ResumeSession_Handler,
		},
		{
			MethodName: "TagMemory",
			Handler:    _OperatorConsole_TagMemory_Handler,
		},
		{
			MethodName: "SetScope",
			Handler:    _OperatorConsole_SetScope_Handler,
		},
		{
			MethodName: "RegisterSkill",
			Handler:    _OperatorConsole_RegisterSkill_Handler,
		},
		{
			MethodName: "RegisterMCP",
			Handler:    _OperatorConsole_RegisterMCP_Handler,
		},
		{
			MethodName: "TriggerConsolidation",
			Handler:    _OperatorConsole_TriggerConsolidation_Handler,
		},
		{
			MethodName: "SetRuntimeConfig",
			Handler:    _OperatorConsole_SetRuntimeConfig_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _OperatorConsole_CreateSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _OperatorConsole_SendMessage_Handler,
		},
		{
			MethodName: "InjectCorrection",
			Handler:    _OperatorConsole_InjectCorrection_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _OperatorConsole_ListTools_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _OperatorConsole_ListSkills_Handler,
		},
		{
			MethodName: "QueryMemory",
			Handler:    _OperatorConsole_QueryMemory_Handler,
		},
		{
			MethodName: "AnswerMemory",
			Handler:    _OperatorConsole_AnswerMemory_Handler,
		},
		{
			MethodName: "SetToolPolicy",
			Handler:    _OperatorConsole_SetToolPolicy_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _OperatorConsole_ExecuteTool_Handler,
		},
		{
			MethodName: "IngestMemory",
			Handler:    _OperatorConsole_IngestMemory_Handler,
		},
		{
			MethodName: "ListWatches",
			Handler:    _OperatorConsole_ListWatches_Handler,
		},
		{
			MethodName: "RegisterWatch",
			Handler:    _OperatorConsole_RegisterWatch_Handler,
		},
		{
			MethodName: "DeleteWatch",
			Handler:    _OperatorConsole_DeleteWatch_Handler,
		},
		{
			MethodName: "SetWatchActive",
			Handler:    _OperatorConsole_SetWatchActive_Handler,
		},
		{
			MethodName: "ListWatchDeadLetters",
			Handler:    _OperatorConsole_ListWatchDeadLetters_Handler,
		},
		{
			MethodName: "GetWatchMetrics",
			Handler:    _OperatorConsole_GetWatchMetrics_Handler,
		},
		{
			MethodName: "BacktestWatch",
			Handler:    _OperatorConsole_BacktestWatch_Handler,
		},
		{
			MethodName: "PreviewRoute",
			Handler:    _OperatorConsole_PreviewRoute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _OperatorConsole_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchToolApprovals",
			Handler:       _OperatorConsole_WatchToolApprovals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "operator.proto",
}
